title: Only Human
theme: minima
permalink: pretty
author: Tom A. Vibeto
github_username: emptyother
linkedin_username: emptyother
facebook_username: emptyother
reddit_username: empty_other
mastodon_url: https://oslo.town/@emptyother
show_excerpts: true
header_pages:
  - blog.html
