title: Only Human
email: post@onlyhuman.dk
description: ""
baseurl: ""
url: ""
theme: "minima"
permalink: pretty
author: Tom A. Vibeto
twitter_username: emptyother
github_username: emptyother
linkedin_username: emptyother
devto_username: emptyother
