title: Only Human
author: Tom A. Vibeto
email: tom@onlyhuman.dk
baseurl: ""
url: onlyhuman.dk
description: >-
  Personal page of emptyother.

theme: minima
plugins:
  - jekyll-feed
  
permalink: pretty
github_username: emptyother
goodreads_username: emptyother
linkedin_username: emptyother
facebook_username: emptyother
reddit_username: empty_other
mastodon_url: https://oslo.town/@emptyother
show_excerpts: true
header_pages:
  - blog/index.md
  - gaming/index.md
