remote-theme: mmistakes/jekyll-theme-basically-basic
title: Only Human
tagline: Tagline
permalink: pretty
author:
  name: Tom A. Vibeto
  email: post@onlyhuman.dk
  github: emptyother

theme: jekyll-theme-minimal