title: Only Human
theme: 'minima'
permalink: pretty
author: Tom A. Vibeto
twitter_username: emptyother
github_username: emptyother
linkedin_username: emptyother
devto_username: emptyother
facebook_username: emptyother
reddit_username: empty_other
show_excerpts: true
header_pages:
    - blog.md
